# Generated by Django 4.0.5 on 2026-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_type', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('stage', models.CharField(choices=[('regular', 'Regular season'), ('playoffs', 'Playoffs')], max_length=10)),
                ('percentiles', models.JSONField(blank=True, default=dict)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20)),
                ('insight_type', models.CharField(choices=[('xg_over_under', 'xG over/underperformance'), ('xg_momentum', 'Trailing-window xG momentum'), ('standout_performer', 'Standout performer vs season pace'), ('goalie_gsax', 'Goalie GSAx'), ('wp_swing', 'Biggest win-probability swing'), ('special_teams_rate', 'In-game special-teams rate vs league average')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('code', models.CharField(max_length=30)),
                ('team', models.CharField(blank=True, max_length=1)),
                ('team_id', models.CharField(blank=True, max_length=20)),
                ('player_id', models.CharField(blank=True, max_length=20)),
                ('period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('abs_time_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('location_x', models.FloatField(blank=True, null=True)),
                ('location_y', models.FloatField(blank=True, null=True)),
                ('xg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('xgot', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('situation', models.CharField(blank=True, choices=[('PP', 'Powerplay'), ('SH', 'Shorthanded'), ('EVEN', 'Even strength')], max_length=4)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('played', 'Played')], default='scheduled', max_length=10)),
                ('team_a_id', models.CharField(blank=True, max_length=20)),
                ('team_b_id', models.CharField(blank=True, max_length=20)),
                ('team_a_name', models.CharField(blank=True, max_length=100)),
                ('team_b_name', models.CharField(blank=True, max_length=100)),
                ('period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_a', models.PositiveSmallIntegerField(default=0)),
                ('score_b', models.PositiveSmallIntegerField(default=0)),
                ('xg_a', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('xg_b', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('xgot_a', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('xgot_b', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('wp_a', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('wp_b', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('last_event_abs_time', models.PositiveIntegerField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostGameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PregameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match_id', 'abs_time_sec'], name='insights_ma_match_i_ed2937_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchevent',
            constraint=models.UniqueConstraint(fields=('match_id', 'event_id'), name='unique_match_event'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['match_id', 'created_at'], name='insights_in_match_i_f590bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalbaseline',
            constraint=models.UniqueConstraint(fields=('baseline_type', 'category', 'stage'), name='unique_baseline_combo'),
        ),
    ]
