# Generated by Django 4.0.5 on 2026-09-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='season_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='stage',
            field=models.CharField(blank=True, choices=[('regular', 'Regular season'), ('playoffs', 'Playoffs')], max_length=10),
        ),
    ]
