# Generated by Django 4.0.5 on 2026-09-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_matchstate_date_matchstate_season_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='situation',
            field=models.CharField(blank=True, choices=[('PP', 'Powerplay'), ('SH', 'Shorthanded'), ('EVEN', 'Even strength'), ('6V5', "Shooting team's own goalie pulled")], max_length=4),
        ),
    ]
