# Generated by Django 4.0.5 on 2026-09-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_alter_matchevent_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('stage', models.CharField(choices=[('regular', 'Regular season'), ('playoffs', 'Playoffs')], max_length=10)),
                ('team_id', models.CharField(max_length=20)),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='teamseasonstats',
            constraint=models.UniqueConstraint(fields=('season_id', 'category', 'stage', 'team_id'), name='unique_team_season_stats'),
        ),
    ]
