# Generated by Django 4.0.5 on 2026-09-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_teamseasonstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('team_id', models.CharField(blank=True, max_length=20)),
                ('player_id', models.CharField(blank=True, max_length=20)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=4)),
                ('line_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_starter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='matchlineup',
            index=models.Index(fields=['match_id', 'team_id'], name='insights_ma_match_i_bc8a5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchlineup',
            constraint=models.UniqueConstraint(fields=('match_id', 'player_id'), name='unique_match_lineup'),
        ),
    ]
