# Generated by Django 4.0.5 on 2026-09-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_matchlineup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='minus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='plus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
