# Generated by Django 4.0.5 on 2026-09-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0006_matchlineup_minus_matchlineup_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='team_a_crest',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='team_b_crest',
            field=models.URLField(blank=True),
        ),
    ]
