# Generated by Django 4.0.5 on 2026-09-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0007_matchlineup_photo_url_matchstate_team_a_crest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('xg_over_under', 'xG over/underperformance'), ('xg_momentum', 'Trailing-window xG momentum'), ('standout_performer', 'Standout performer vs season pace'), ('goalie_gsax', 'Goalie GSAx'), ('wp_swing', 'Biggest win-probability swing'), ('special_teams_rate', 'In-game special-teams rate vs league average'), ('against_the_odds', 'Leading on the scoreboard despite a worse win probability'), ('line_battle', '5v5 line-vs-line xG/goal gap'), ('special_teams_battle', 'Head-to-head power-play goal differential'), ('penalty_discipline', 'Penalty count gap between the two teams'), ('goalie_duel', 'Head-to-head GSAx between the two starting goalies')], max_length=30),
        ),
    ]
