# Generated by Django 4.0.5 on 2026-09-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0008_alter_insight_insight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('xg_over_under', 'xG over/underperformance'), ('xg_momentum', 'Trailing-window xG momentum'), ('standout_performer', 'Standout performer vs season pace'), ('goalie_gsax', 'Goalie GSAx'), ('wp_swing', 'Biggest win-probability swing'), ('special_teams_rate', 'In-game special-teams rate vs league average'), ('against_the_odds', 'Leading on the scoreboard despite a worse win probability'), ('line_battle', '5v5 line-vs-line xG/goal gap'), ('special_teams_battle', 'Head-to-head power-play goal differential'), ('penalty_discipline', 'Penalty count gap between the two teams'), ('goalie_duel', 'Head-to-head GSAx between the two starting goalies'), ('comeback', 'Biggest deficit overcome by the current leader'), ('lead_change', 'Number of times the lead has changed hands'), ('balanced_scoring', 'Goals spread across many different players'), ('clean_sweep', 'Every line individually ahead of its counterpart')], max_length=30),
        ),
    ]
