"""
Django settings for Floorballscanner project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

import django_heroku
import dj_database_url
import dotenv
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    )

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

# This is new:
dotenv_file = os.path.join(BASE_DIR, ".env")
if os.path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    '!bxves#1y8oy5trf7_kmc*z)-_1tyv77trs)4b#wm4w06w4x^!',  # local-dev fallback only
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults preserve current (pre-refactor) behavior so this change is a no-op until
# DEBUG / ALLOWED_HOSTS config vars are explicitly set per environment (see staging plan).
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'analyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.license_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'analyzer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {}
DATABASES['default'] = dj_database_url.config(conn_max_age=600)

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


LOGIN_REDIRECT_URL = 'home' # Redirect to views.function Name = "home"
LOGOUT_REDIRECT_URL = 'frontpage' # Redirect to views.function Name = "frontpage"

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}

django_heroku.settings(locals())

# This is new
options = DATABASES['default'].get('OPTIONS', {})
options.pop('sslmode', None)

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.SessionAuthentication',
        #'rest_framework.authentication.BasicAuthentication',
    ]
}

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

# EXTRA_CORS_ORIGINS / EXTRA_CSRF_TRUSTED_ORIGINS let a non-production environment (e.g.
# staging on a *.herokuapp.com domain) add its own origin without touching the production list.
CORS_ORIGIN_WHITELIST = (
    'http://localhost:3000',  # for localhost (REACT Default)
    'http://192.168.0.50:3000',  # for network
    'http://localhost:8080',  # for localhost (Developlemt)
    'http://192.168.0.50:8080',  # for network (Development)
    'https://*.fbscanner.io',
) + tuple(filter(None, os.environ.get('EXTRA_CORS_ORIGINS', '').split(',')))

CSRF_TRUSTED_ORIGINS = [
    'https://fbscanner.io/livedata',
    'https://www.fbscanner.io/livedata',
    'https://*.fbscanner.io',
] + list(filter(None, os.environ.get('EXTRA_CSRF_TRUSTED_ORIGINS', '').split(',')))

CSRF_COOKIE_DOMAIN = os.environ.get('CSRF_COOKIE_DOMAIN', '.fbscanner.io')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'

# Site root used to build absolute links (e.g. license activation emails) outside of a
# request context, such as in management commands.
SITE_URL = os.environ.get('SITE_URL', 'https://fbscanner.io')

# Defaults to printing emails to the console/log so no environment ever sends real email
# unless EMAIL_HOST_USER/EMAIL_HOST_PASSWORD are explicitly set (production only, via
# Gmail SMTP + an account App Password — not the regular Gmail password).
if os.environ.get('EMAIL_HOST_USER'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
    EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'floorballscanner@gmail.com'

# Stripe: kept unset (empty string) in any environment that hasn't configured it yet, so
# views can check `if not settings.STRIPE_SECRET_KEY` rather than crashing on import.
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# One Stripe Price ID per license tier, set via Heroku config vars once the Price objects
# exist in the Stripe Dashboard (test mode first, then live mode after go-live).
STRIPE_PRICE_IDS = {
    'team': os.environ.get('STRIPE_PRICE_ID_TEAM', ''),
    'club': os.environ.get('STRIPE_PRICE_ID_CLUB', ''),
    'fliiga': os.environ.get('STRIPE_PRICE_ID_FLIIGA', ''),
}

# Stripe File id (purpose='business_icon') for the Checkout page's brand icon — the
# logo files in static/ have a white wordmark meant for the navy nav bar, which is
# invisible on Checkout's light background, so only the icon (no wordmark) is used
# there; the business name is shown as text instead via branding_settings.display_name.
STRIPE_BRANDING_ICON_FILE_ID = os.environ.get('STRIPE_BRANDING_ICON_FILE_ID', '')
