# This is the file where Django backend models = database tables are created

from django.db import models
import uuid

# Create your models here

class Player(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    jersey_number = models.IntegerField()
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name} ({self.first_name})'

class Live(models.Model):
    objects = models.Manager()
    data = models.JSONField()
    #data = models.IntegerField()

    def __str__(self):
        return self.data

class Team(models.Model):
    objects = models.Manager()

    name = models.CharField(max_length=100)
    lineOn = models.IntegerField()
    possessionPeriod = models.IntegerField()
    possessionGame = models.IntegerField()
    goalsPeriod = models.IntegerField()
    goalsGame = models.IntegerField()
    xgPeriod = models.DecimalField(max_digits=5, decimal_places=2)
    xgGame = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

class Game(models.Model):
    objects = models.Manager()
    
    # Game variables
    date = models.DateTimeField(auto_now = True, blank = True)
    periodNr = models.IntegerField()
    gameClock = models.IntegerField()
    periodClock = models.IntegerField()
    
    # Team variables
    nameT1 = models.CharField(max_length=50)
    lineOnT1 = models.IntegerField()
    possessionPeriodT1 = models.IntegerField()
    possessionGameT1 = models.IntegerField()
    goalsPeriodT1 = models.IntegerField()
    goalsGameT1 = models.IntegerField()
    xGPeriodT1 = models.DecimalField(max_digits=5, decimal_places=2)
    xGGameT1 = models.DecimalField(max_digits=5, decimal_places=2)
    nameT2 = models.CharField(max_length=50)
    lineOnT2 = models.IntegerField()
    possessionPeriodT2 = models.IntegerField()
    possessionGameT2 = models.IntegerField()
    goalsPeriodT2 = models.IntegerField()
    goalsGameT2 = models.IntegerField()
    xGPeriodT2 = models.DecimalField(max_digits=5, decimal_places=2)
    xGGameT2 = models.DecimalField(max_digits=5, decimal_places=2)
    
    # Line variables
    nameL1 = models.CharField(max_length=50)
    possessionPeriodT1L1 = models.IntegerField()
    possessionGameT1L1 = models.IntegerField()
    gfPeriodT1L1 = models.IntegerField()
    gfGameT1L1 = models.IntegerField()
    gaPeriodT1L1 = models.IntegerField()
    gaGameT1L1 = models.IntegerField()
    TOCPeriodT1L1 = models.IntegerField()
    TOCGameT1L1 = models.IntegerField()
    xGfPeriodT1L1 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT1L1 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT1L1 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT1L1 = models.DecimalField(max_digits=5, decimal_places=2)
    possessionPeriodT2L1 = models.IntegerField()
    possessionGameT2L1 = models.IntegerField()
    gfPeriodT2L1 = models.IntegerField()
    gfGameT2L1 = models.IntegerField()
    gaPeriodT2L1 = models.IntegerField()
    gaGameT2L1 = models.IntegerField()
    TOCPeriodT2L1 = models.IntegerField()
    TOCGameT2L1 = models.IntegerField()
    xGfPeriodT2L1 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT2L1 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT2L1 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT2L1 = models.DecimalField(max_digits=5, decimal_places=2)

    nameL2 = models.CharField(max_length=50)
    possessionPeriodT1L2 = models.IntegerField()
    possessionGameT1L2 = models.IntegerField()
    gfPeriodT1L2 = models.IntegerField()
    gfGameT1L2 = models.IntegerField()
    gaPeriodT1L2 = models.IntegerField()
    gaGameT1L2 = models.IntegerField()
    TOCPeriodT1L2 = models.IntegerField()
    TOCGameT1L2 = models.IntegerField()
    xGfPeriodT1L2 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT1L2 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT1L2 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT1L2 = models.DecimalField(max_digits=5, decimal_places=2)
    possessionPeriodT2L2 = models.IntegerField()
    possessionGameT2L2 = models.IntegerField()
    gfPeriodT2L2 = models.IntegerField()
    gfGameT2L2 = models.IntegerField()
    gaPeriodT2L2 = models.IntegerField()
    gaGameT2L2 = models.IntegerField()
    TOCPeriodT2L2 = models.IntegerField()
    TOCGameT2L2 = models.IntegerField()
    xGfPeriodT2L2 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT2L2 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT2L2 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT2L2 = models.DecimalField(max_digits=5, decimal_places=2)

    nameL3 = models.CharField(max_length=50)
    possessionPeriodT1L3 = models.IntegerField()
    possessionGameT1L3 = models.IntegerField()
    gfPeriodT1L3 = models.IntegerField()
    gfGameT1L3 = models.IntegerField()
    gaPeriodT1L3 = models.IntegerField()
    gaGameT1L3 = models.IntegerField()
    TOCPeriodT1L3 = models.IntegerField()
    TOCGameT1L3 = models.IntegerField()
    xGfPeriodT1L3 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT1L3 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT1L3 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT1L3 = models.DecimalField(max_digits=5, decimal_places=2)
    possessionPeriodT2L3 = models.IntegerField()
    possessionGameT2L3 = models.IntegerField()
    gfPeriodT2L3 = models.IntegerField()
    gfGameT2L3 = models.IntegerField()
    gaPeriodT2L3 = models.IntegerField()
    gaGameT2L3 = models.IntegerField()
    TOCPeriodT2L3 = models.IntegerField()
    TOCGameT2L3 = models.IntegerField()
    xGfPeriodT2L3 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT2L3 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT2L3 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT2L3 = models.DecimalField(max_digits=5, decimal_places=2)

    nameL4 = models.CharField(max_length=50)
    possessionPeriodT1L4 = models.IntegerField()
    possessionGameT1L4 = models.IntegerField()
    gfPeriodT1L4 = models.IntegerField()
    gfGameT1L4 = models.IntegerField()
    gaPeriodT1L4 = models.IntegerField()
    gaGameT1L4 = models.IntegerField()
    TOCPeriodT1L4 = models.IntegerField()
    TOCGameT1L4 = models.IntegerField()
    xGfPeriodT1L4 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT1L4 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT1L4 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT1L4 = models.DecimalField(max_digits=5, decimal_places=2)
    possessionPeriodT2L4 = models.IntegerField()
    possessionGameT2L4 = models.IntegerField()
    gfPeriodT2L4 = models.IntegerField()
    gfGameT2L4 = models.IntegerField()
    gaPeriodT2L4 = models.IntegerField()
    gaGameT2L4 = models.IntegerField()
    TOCPeriodT2L4 = models.IntegerField()
    TOCGameT2L4 = models.IntegerField()
    xGfPeriodT2L4 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT2L4 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT2L4 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT2L4 = models.DecimalField(max_digits=5, decimal_places=2)

    nameL5 = models.CharField(max_length=50)
    possessionPeriodT1L5 = models.IntegerField()
    possessionGameT1L5 = models.IntegerField()
    gfPeriodT1L5 = models.IntegerField()
    gfGameT1L5 = models.IntegerField()
    gaPeriodT1L5 = models.IntegerField()
    gaGameT1L5 = models.IntegerField()
    TOCPeriodT1L5 = models.IntegerField()
    TOCGameT1L5 = models.IntegerField()
    xGfPeriodT1L5 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT1L5 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT1L5 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT1L5 = models.DecimalField(max_digits=5, decimal_places=2)
    possessionPeriodT2L5 = models.IntegerField()
    possessionGameT2L5 = models.IntegerField()
    gfPeriodT2L5 = models.IntegerField()
    gfGameT2L5 = models.IntegerField()
    gaPeriodT2L5 = models.IntegerField()
    gaGameT2L5 = models.IntegerField()
    TOCPeriodT2L5 = models.IntegerField()
    TOCGameT2L5 = models.IntegerField()
    xGfPeriodT2L5 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT2L5 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT2L5 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT2L5 = models.DecimalField(max_digits=5, decimal_places=2)

    nameL6 = models.CharField(max_length=50)
    possessionPeriodT1L6 = models.IntegerField()
    possessionGameT1L6 = models.IntegerField()
    gfPeriodT1L6 = models.IntegerField()
    gfGameT1L6 = models.IntegerField()
    gaPeriodT1L6 = models.IntegerField()
    gaGameT1L6 = models.IntegerField()
    TOCPeriodT1L6 = models.IntegerField()
    TOCGameT1L6 = models.IntegerField()
    xGfPeriodT1L6 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT1L6 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT1L6 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT1L6 = models.DecimalField(max_digits=5, decimal_places=2)
    possessionPeriodT2L6 = models.IntegerField()
    possessionGameT2L6 = models.IntegerField()
    gfPeriodT2L6 = models.IntegerField()
    gfGameT2L6 = models.IntegerField()
    gaPeriodT2L6 = models.IntegerField()
    gaGameT2L6 = models.IntegerField()
    TOCPeriodT2L6 = models.IntegerField()
    TOCGameT2L6 = models.IntegerField()
    xGfPeriodT2L6 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT2L6 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT2L6 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT2L6 = models.DecimalField(max_digits=5, decimal_places=2)

    nameL7 = models.CharField(max_length=50)
    possessionPeriodT1L7 = models.IntegerField()
    possessionGameT1L7 = models.IntegerField()
    gfPeriodT1L7 = models.IntegerField()
    gfGameT1L7 = models.IntegerField()
    gaPeriodT1L7 = models.IntegerField()
    gaGameT1L7 = models.IntegerField()
    TOCPeriodT1L7 = models.IntegerField()
    TOCGameT1L7 = models.IntegerField()
    xGfPeriodT1L7 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT1L7 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT1L7 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT1L7 = models.DecimalField(max_digits=5, decimal_places=2)
    possessionPeriodT2L7 = models.IntegerField()
    possessionGameT2L7 = models.IntegerField()
    gfPeriodT2L7 = models.IntegerField()
    gfGameT2L7 = models.IntegerField()
    gaPeriodT2L7 = models.IntegerField()
    gaGameT2L7 = models.IntegerField()
    TOCPeriodT2L7 = models.IntegerField()
    TOCGameT2L7 = models.IntegerField()
    xGfPeriodT2L7 = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGameT2L7 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriodT2L7 = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGameT2L7 = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.date

class Line(models.Model):
    name = models.CharField(max_length=20)
    possessionPeriod = models.IntegerField()
    possessionGame = models.IntegerField()
    gfPeriod = models.IntegerField()
    gfGame = models.IntegerField()
    gaPeriod = models.IntegerField()
    gaGame = models.IntegerField()
    TOCPeriod = models.IntegerField()
    TOCGame = models.IntegerField()
    xGfPeriod = models.DecimalField(max_digits=5, decimal_places=2)
    xGfGame = models.DecimalField(max_digits=5, decimal_places=2)
    xGaPeriod = models.DecimalField(max_digits=5, decimal_places=2)
    xGaGame = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name