# Generated by Django 4.0.5 on 2026-09-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('analytics-101', 'Analytics 101'), ('coaching-guides', 'Coaching Guides'), ('product', 'Product & Data')], max_length=20)),
                ('excerpt', models.CharField(max_length=300)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('cover_image', models.URLField(blank=True)),
                ('body', models.TextField()),
                ('faq', models.JSONField(blank=True, default=list)),
                ('author', models.CharField(default='Floorball Scanner Team', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
