# Generated by Django 3.1.6 on 2022-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('periodNr', models.IntegerField()),
                ('gameClock', models.IntegerField()),
                ('periodClock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('possessionPeriod', models.IntegerField()),
                ('possessionGame', models.IntegerField()),
                ('gfPeriod', models.IntegerField()),
                ('gfGame', models.IntegerField()),
                ('gaPeriod', models.IntegerField()),
                ('gaGame', models.IntegerField()),
                ('TOCPeriod', models.IntegerField()),
                ('TOCGame', models.IntegerField()),
                ('xGfPeriod', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xGfGame', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xGaPeriod', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xGaGame', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lineOn', models.IntegerField()),
                ('possessionPeriod', models.IntegerField()),
                ('possessionGame', models.IntegerField()),
                ('goalsPeriod', models.IntegerField()),
                ('goalsGame', models.IntegerField()),
                ('xgPeriod', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xgGame', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
