# Generated by Django 4.0.5 on 2022-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_live_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='data',
            field=models.IntegerField(),
        ),
    ]
