# Generated by Django 4.0.5 on 2022-06-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_game_tocgamet1l1_game_tocgamet1l2_game_tocgamet1l3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Live',
        ),
    ]
