# Generated by Django 4.0.5 on 2022-06-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_live'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Live',
        ),
    ]
