# Generated by Django 4.0.5 on 2022-07-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_line_abbr_line_name_position_abbr_position_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='line',
        ),
        migrations.AddField(
            model_name='player',
            name='line',
            field=models.ManyToManyField(blank=True, to='accounts.line'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, default=99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(blank=True, to='accounts.position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.level'),
        ),
    ]
