# Generated by Django 4.0.5 on 2022-07-26 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_remove_team_line_player_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('periodNr', models.IntegerField(null=True)),
                ('gameClock', models.IntegerField(null=True)),
                ('periodClock', models.IntegerField(null=True)),
                ('nameT1', models.CharField(max_length=50, null=True)),
                ('lineOnT1', models.IntegerField(null=True)),
                ('possessionPeriodT1', models.IntegerField(null=True)),
                ('possessionGameT1', models.IntegerField(null=True)),
                ('goalsPeriodT1', models.IntegerField(null=True)),
                ('goalsGameT1', models.IntegerField(null=True)),
                ('xGPeriodT1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGGameT1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nameT2', models.CharField(max_length=50, null=True)),
                ('lineOnT2', models.IntegerField(null=True)),
                ('possessionPeriodT2', models.IntegerField(null=True)),
                ('possessionGameT2', models.IntegerField(null=True)),
                ('goalsPeriodT2', models.IntegerField(null=True)),
                ('goalsGameT2', models.IntegerField(null=True)),
                ('xGPeriodT2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGGameT2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nameL1', models.CharField(max_length=50, null=True)),
                ('possessionPeriodT1L1', models.IntegerField(null=True)),
                ('possessionGameT1L1', models.IntegerField(null=True)),
                ('gfPeriodT1L1', models.IntegerField(null=True)),
                ('gfGameT1L1', models.IntegerField(null=True)),
                ('gaPeriodT1L1', models.IntegerField(null=True)),
                ('gaGameT1L1', models.IntegerField(null=True)),
                ('TOCPeriodT1L1', models.IntegerField(null=True)),
                ('TOCGameT1L1', models.IntegerField(null=True)),
                ('xGfPeriodT1L1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT1L1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT1L1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT1L1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('possessionPeriodT2L1', models.IntegerField(null=True)),
                ('possessionGameT2L1', models.IntegerField(null=True)),
                ('gfPeriodT2L1', models.IntegerField(null=True)),
                ('gfGameT2L1', models.IntegerField(null=True)),
                ('gaPeriodT2L1', models.IntegerField(null=True)),
                ('gaGameT2L1', models.IntegerField(null=True)),
                ('TOCPeriodT2L1', models.IntegerField(null=True)),
                ('TOCGameT2L1', models.IntegerField(null=True)),
                ('xGfPeriodT2L1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT2L1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT2L1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT2L1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nameL2', models.CharField(max_length=50, null=True)),
                ('possessionPeriodT1L2', models.IntegerField(null=True)),
                ('possessionGameT1L2', models.IntegerField(null=True)),
                ('gfPeriodT1L2', models.IntegerField(null=True)),
                ('gfGameT1L2', models.IntegerField(null=True)),
                ('gaPeriodT1L2', models.IntegerField(null=True)),
                ('gaGameT1L2', models.IntegerField(null=True)),
                ('TOCPeriodT1L2', models.IntegerField(null=True)),
                ('TOCGameT1L2', models.IntegerField(null=True)),
                ('xGfPeriodT1L2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT1L2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT1L2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT1L2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('possessionPeriodT2L2', models.IntegerField(null=True)),
                ('possessionGameT2L2', models.IntegerField(null=True)),
                ('gfPeriodT2L2', models.IntegerField(null=True)),
                ('gfGameT2L2', models.IntegerField(null=True)),
                ('gaPeriodT2L2', models.IntegerField(null=True)),
                ('gaGameT2L2', models.IntegerField(null=True)),
                ('TOCPeriodT2L2', models.IntegerField(null=True)),
                ('TOCGameT2L2', models.IntegerField(null=True)),
                ('xGfPeriodT2L2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT2L2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT2L2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT2L2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nameL3', models.CharField(max_length=50, null=True)),
                ('possessionPeriodT1L3', models.IntegerField(null=True)),
                ('possessionGameT1L3', models.IntegerField(null=True)),
                ('gfPeriodT1L3', models.IntegerField(null=True)),
                ('gfGameT1L3', models.IntegerField(null=True)),
                ('gaPeriodT1L3', models.IntegerField(null=True)),
                ('gaGameT1L3', models.IntegerField(null=True)),
                ('TOCPeriodT1L3', models.IntegerField(null=True)),
                ('TOCGameT1L3', models.IntegerField(null=True)),
                ('xGfPeriodT1L3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT1L3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT1L3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT1L3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('possessionPeriodT2L3', models.IntegerField(null=True)),
                ('possessionGameT2L3', models.IntegerField(null=True)),
                ('gfPeriodT2L3', models.IntegerField(null=True)),
                ('gfGameT2L3', models.IntegerField(null=True)),
                ('gaPeriodT2L3', models.IntegerField(null=True)),
                ('gaGameT2L3', models.IntegerField(null=True)),
                ('TOCPeriodT2L3', models.IntegerField(null=True)),
                ('TOCGameT2L3', models.IntegerField(null=True)),
                ('xGfPeriodT2L3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT2L3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT2L3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT2L3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nameL4', models.CharField(max_length=50, null=True)),
                ('possessionPeriodT1L4', models.IntegerField(null=True)),
                ('possessionGameT1L4', models.IntegerField(null=True)),
                ('gfPeriodT1L4', models.IntegerField(null=True)),
                ('gfGameT1L4', models.IntegerField(null=True)),
                ('gaPeriodT1L4', models.IntegerField(null=True)),
                ('gaGameT1L4', models.IntegerField(null=True)),
                ('TOCPeriodT1L4', models.IntegerField(null=True)),
                ('TOCGameT1L4', models.IntegerField(null=True)),
                ('xGfPeriodT1L4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT1L4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT1L4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT1L4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('possessionPeriodT2L4', models.IntegerField(null=True)),
                ('possessionGameT2L4', models.IntegerField(null=True)),
                ('gfPeriodT2L4', models.IntegerField(null=True)),
                ('gfGameT2L4', models.IntegerField(null=True)),
                ('gaPeriodT2L4', models.IntegerField(null=True)),
                ('gaGameT2L4', models.IntegerField(null=True)),
                ('TOCPeriodT2L4', models.IntegerField(null=True)),
                ('TOCGameT2L4', models.IntegerField(null=True)),
                ('xGfPeriodT2L4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT2L4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT2L4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT2L4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nameL5', models.CharField(max_length=50, null=True)),
                ('possessionPeriodT1L5', models.IntegerField(null=True)),
                ('possessionGameT1L5', models.IntegerField(null=True)),
                ('gfPeriodT1L5', models.IntegerField(null=True)),
                ('gfGameT1L5', models.IntegerField(null=True)),
                ('gaPeriodT1L5', models.IntegerField(null=True)),
                ('gaGameT1L5', models.IntegerField(null=True)),
                ('TOCPeriodT1L5', models.IntegerField(null=True)),
                ('TOCGameT1L5', models.IntegerField(null=True)),
                ('xGfPeriodT1L5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT1L5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT1L5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT1L5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('possessionPeriodT2L5', models.IntegerField(null=True)),
                ('possessionGameT2L5', models.IntegerField(null=True)),
                ('gfPeriodT2L5', models.IntegerField(null=True)),
                ('gfGameT2L5', models.IntegerField(null=True)),
                ('gaPeriodT2L5', models.IntegerField(null=True)),
                ('gaGameT2L5', models.IntegerField(null=True)),
                ('TOCPeriodT2L5', models.IntegerField(null=True)),
                ('TOCGameT2L5', models.IntegerField(null=True)),
                ('xGfPeriodT2L5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT2L5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT2L5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT2L5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nameL6', models.CharField(max_length=50, null=True)),
                ('possessionPeriodT1L6', models.IntegerField(null=True)),
                ('possessionGameT1L6', models.IntegerField(null=True)),
                ('gfPeriodT1L6', models.IntegerField(null=True)),
                ('gfGameT1L6', models.IntegerField(null=True)),
                ('gaPeriodT1L6', models.IntegerField(null=True)),
                ('gaGameT1L6', models.IntegerField(null=True)),
                ('TOCPeriodT1L6', models.IntegerField(null=True)),
                ('TOCGameT1L6', models.IntegerField(null=True)),
                ('xGfPeriodT1L6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT1L6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT1L6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT1L6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('possessionPeriodT2L6', models.IntegerField(null=True)),
                ('possessionGameT2L6', models.IntegerField(null=True)),
                ('gfPeriodT2L6', models.IntegerField(null=True)),
                ('gfGameT2L6', models.IntegerField(null=True)),
                ('gaPeriodT2L6', models.IntegerField(null=True)),
                ('gaGameT2L6', models.IntegerField(null=True)),
                ('TOCPeriodT2L6', models.IntegerField(null=True)),
                ('TOCGameT2L6', models.IntegerField(null=True)),
                ('xGfPeriodT2L6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT2L6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT2L6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT2L6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nameL7', models.CharField(max_length=50, null=True)),
                ('possessionPeriodT1L7', models.IntegerField(null=True)),
                ('possessionGameT1L7', models.IntegerField(null=True)),
                ('gfPeriodT1L7', models.IntegerField(null=True)),
                ('gfGameT1L7', models.IntegerField(null=True)),
                ('gaPeriodT1L7', models.IntegerField(null=True)),
                ('gaGameT1L7', models.IntegerField(null=True)),
                ('TOCPeriodT1L7', models.IntegerField(null=True)),
                ('TOCGameT1L7', models.IntegerField(null=True)),
                ('xGfPeriodT1L7', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT1L7', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT1L7', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT1L7', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('possessionPeriodT2L7', models.IntegerField(null=True)),
                ('possessionGameT2L7', models.IntegerField(null=True)),
                ('gfPeriodT2L7', models.IntegerField(null=True)),
                ('gfGameT2L7', models.IntegerField(null=True)),
                ('gaPeriodT2L7', models.IntegerField(null=True)),
                ('gaGameT2L7', models.IntegerField(null=True)),
                ('TOCPeriodT2L7', models.IntegerField(null=True)),
                ('TOCGameT2L7', models.IntegerField(null=True)),
                ('xGfPeriodT2L7', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGfGameT2L7', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaPeriodT2L7', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('xGaGameT2L7', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCGameT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOCPeriodT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaGameT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaPeriodT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gameClock',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfGameT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gfPeriodT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='goalsGameT1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='goalsGameT2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='goalsPeriodT1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='goalsPeriodT2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='lineOnT1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='lineOnT2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameL1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameL2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameL3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameL4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameL5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameL6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameL7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameT1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nameT2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='periodClock',
        ),
        migrations.RemoveField(
            model_name='game',
            name='periodNr',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionGameT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possessionPeriodT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGGameT1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGGameT2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGPeriodT1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGPeriodT2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaGameT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGaPeriodT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfGameT2L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT1L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT1L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT1L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT1L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT1L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT1L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT1L7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT2L1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT2L2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT2L3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT2L4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT2L5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT2L6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xGfPeriodT2L7',
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='accounts.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
    ]
