# Generated by Django 4.0.5 on 2022-07-31 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_remove_game_user_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='T1C',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T1G',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T1LD',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T1LW',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T1RD',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T1RW',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T2C',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T2G',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T2LD',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T2LW',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T2RD',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='T2RW',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.game'),
        ),
        migrations.AddField(
            model_name='shot',
            name='passer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='shooter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
