# Generated by Django 4.0.5 on 2022-08-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='toGameT1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toGameT1L1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toGameT1L2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toGameT1L3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toGameT2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toGameT2L1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toGameT2L2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toGameT2L3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toPeriodT1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toPeriodT1L1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toPeriodT1L2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toPeriodT1L3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toPeriodT2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toPeriodT2L1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toPeriodT2L2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='toPeriodT2L3',
            field=models.IntegerField(null=True),
        ),
    ]
