# Generated by Django 4.0.5 on 2022-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_livedata_togamet1_livedata_togamet1l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
