# Generated by Django 4.0.5 on 2026-08-30 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0023_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='license',
            name='email',
        ),
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
        migrations.AddField(
            model_name='license',
            name='max_seats',
            field=models.PositiveIntegerField(blank=True, help_text='1 for Team/F-Liiga. Leave blank for Club (unlimited seats).', null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='tier',
            field=models.CharField(choices=[('fliiga', 'F-Liiga'), ('team', 'Team'), ('club', 'Club')], max_length=10),
        ),
        migrations.CreateModel(
            name='LicenseSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('activation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='accounts.license')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
