# Generated by Django 4.0.5 on 2026-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_license_activation_token_remove_license_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='max_seats',
            field=models.PositiveIntegerField(blank=True, help_text='1 for Team/F-Liiga/Trial. Leave blank for Club (unlimited seats).', null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='tier',
            field=models.CharField(choices=[('trial', 'Trial'), ('fliiga', 'F-Liiga'), ('team', 'Team'), ('club', 'Club')], max_length=10),
        ),
    ]
