# Generated by Django 4.0.5 on 2026-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_license_max_seats_alter_license_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FliigaSeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('stage', models.CharField(choices=[('regular', 'Regular season'), ('playoffs', 'Playoffs')], max_length=10)),
                ('team_stats', models.JSONField(default=list)),
                ('player_stats', models.JSONField(default=list)),
                ('goalie_stats', models.JSONField(default=list)),
                ('is_final', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='fliigaseasonstats',
            constraint=models.UniqueConstraint(fields=('season_id', 'category', 'stage'), name='unique_fliiga_stats_combo'),
        ),
    ]
