# Generated by Django 4.0.5 on 2026-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_license_max_seats_alter_license_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='max_seats',
            field=models.PositiveIntegerField(blank=True, help_text='1 for Team/F-Liiga Live/F-Liiga Full/Trial/F-Liiga Trial. Leave blank for Club (unlimited seats).', null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='tier',
            field=models.CharField(choices=[('trial', 'Trial'), ('fliiga_trial', 'F-Liiga Trial'), ('fliiga', 'F-Liiga Live'), ('fliiga_full', 'F-Liiga Full'), ('team', 'Team'), ('club', 'Club')], max_length=15),
        ),
    ]
