# Generated by Django 4.0.5 on 2026-09-27 09:00

from django.db import migrations, models


def mark_existing_games_completed(apps, schema_editor):
    # Autosave/resume (and the 'status' field itself) didn't exist before this migration - every
    # Game row already in the database was created exclusively by the old one-shot final save, so
    # every one of them is a finished game. The AddField above defaults new rows (going forward)
    # to 'in_progress', which would otherwise also apply to all this pre-existing history and
    # wrongly clutter the new "Resume" list with already-finished games.
    Game = apps.get_model('accounts', 'Game')
    Game.objects.update(status='completed')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_license_max_seats_alter_license_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(mark_existing_games_completed, migrations.RunPython.noop),
    ]
